services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8003:8000"
    volumes:
      - chroma_data:/chroma/chroma

  mock-api:
    build: ./backend/mock-api
    ports:
      - "8002:8002"

  integration-service:
    build: ./backend/integration-service
    ports:
      - "8000:8000"
    depends_on:
      - mock-api

  orchestrator-service:
    build: ./backend/orchestrator-service
    ports:
      - "8001:8001"
    depends_on:
      - mock-api
      - integration-service
      - chromadb
    env_file:
      - .env

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - orchestrator-service

  frontend-jalan:
    build:
      context: ./frontend-jalan
      args:
        - VITE_API_URL=http://localhost:8080
    ports:
      - "5173:5173"
    depends_on:
      - api-gateway

  frontend-pesan:
    build: ./frontend-pesan
    ports:
      - "5174:5174"

volumes:
  chroma_data:
